# Change these first
owner: mswd-io # Your GitHub username
repo: upptime # Your Github repository name
user-agent: mswd-upptime

# Add your sites here
sites:
  - name: YourFleece
    url: https://yourfleece.com
  - name: YourCotton
    url: https://cottonfabric.com
  - name: Kalon Studios
    url: https://kalonstudios.com
  - name: CoreEM
    url: https://coreem.net
  - name: LAG+USC EM
    url: https://laguscem.com
  # - name: BN/SEM
    # url: https://socialem.net
  - name: Giantmecha
    url: https://giantmecha.com
  - name: Stress Positions
    url: https://stresspositions.com

assignees: # Users to assign downtime issues (optional)
  - shamoon

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.mswd.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /mswd-upptime
  logoUrl: https://mswd.io/wp-content/uploads/2019/03/mswd_logo.svg
  name: MSWD Status
  introTitle: "**MSWD** uptime monitor and status page."
  introMessage: Status uses **real-time** data.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
